#!/bin/bash

# SANITY CMS QUICK START SCRIPT
# This file contains all commands needed to set up Sanity

echo "🚀 SANITY CMS SETUP FOR LOBO TUFTING"
echo "===================================="
echo ""

# Step 1: Install dependencies
echo "Step 1: Checking dependencies..."
if ! command -v sanity &> /dev/null; then
    echo "Installing Sanity CLI globally..."
    npm install -g @sanity/cli
else
    echo "✓ Sanity CLI already installed"
fi

echo ""
echo "Step 2: Create your Sanity project"
echo "===================================="
echo ""
echo "1. Go to https://sanity.io"
echo "2. Sign up or log in"
echo "3. Create a new project named 'lobo-tufting-cms'"
echo "4. Copy your Project ID"
echo ""
echo "Once you have your Project ID, run:"
echo "cd /Users/zn/Documents/Lobo-website-v1/lobo-tufting"
echo "export SANITY_PROJECT_ID=your_project_id_here"
echo ""

echo "Step 3: Set up Sanity Studio"
echo "============================="
echo ""
echo "Run these commands:"
echo "sanity login"
echo "cd /Users/zn/Documents/Lobo-website-v1/lobo-tufting/studio"
echo "npm install"
echo "npm run dev"
echo ""
echo "(Do NOT run 'sanity init studio' — that command is outdated.)"
echo ""

echo "Step 4: Configure API Token"
echo "============================"
echo ""
echo "1. Go to your Sanity project settings"
echo "2. Navigate to: Settings → API Tokens"
echo "3. Click 'Add New Token'"
echo "4. Name: 'Lobo Frontend Read'"
echo "5. Permission: Editor"
echo "6. Generate token and copy it"
echo ""

echo "Step 5: Create .env.local"
echo "=========================="
echo ""
echo "Create file: /Users/zn/Documents/Lobo-website-v1/lobo-tufting/.env.local"
echo ""
echo "VITE_SANITY_PROJECT_ID=your_project_id"
echo "VITE_SANITY_DATASET=production"
echo "VITE_SANITY_TOKEN=your_read_token"
echo ""

echo "Step 6: Start Sanity Studio"
echo "==========================="
echo ""
echo "cd studio"
echo "npm run dev"
echo ""
echo "Visit: http://localhost:3333"
echo ""

echo "Step 7: Create Document Types"
echo "=============================="
echo ""
echo "In Sanity Studio, create these document types using Studio UI:"
echo ""
echo "- hero (Homepage hero section)"
echo "- gallery (Portfolio items)"
echo "- product (Shop products)"
echo "- workshopItem (Workshop listings)"
echo "- about (About page)"
echo "- testimonial (Client reviews)"
echo "- settings (Site settings)"
echo ""
echo "See: src/sanity/schema.ts for field definitions"
echo ""

echo "Step 8: Add Sample Content"
echo "=========================="
echo ""
echo "1. Create at least 1 'hero' document"
echo "2. Add 3-5 'gallery' items"
echo "3. Add 2-3 'product' items"
echo "4. Add 1 'workshopItem'"
echo "5. Create 1 'about' document"
echo ""
echo "IMPORTANT: Upload images via Sanity's image field"
echo ""

echo "Step 9: Test the Integration"
echo "============================"
echo ""
echo "Open new terminal:"
echo "cd /Users/zn/Documents/Lobo-website-v1/lobo-tufting"
echo "npm run dev"
echo ""
echo "Visit: http://localhost:3000"
echo "Check that images and content load from Sanity"
echo ""

echo "✅ SETUP COMPLETE!"
echo ""
echo "For detailed information, see:"
echo "- SANITY_SETUP_GUIDE.txt"
echo "- SANITY_INTEGRATION_COMPLETE.md"
echo "- src/sanity/README.md"
